package view;

public enum CommandsEnum {
    USERNAME_FORMAT_INVALID,
    EMPTY_FIELD,
    USERNAME_EXISTS,
    LENGTH_WEEK_PASSWORD,
    CAPITAL_LETTERS,
    SMALL_LETTERS,
    NUMBER_NOT_EXISTS,
    INVALID_SPECIAL_CHARACTER,
    PASSWORD_CONFIRMATION_INCORRECT,
    EMAIL_EXISTS,
    EMAIL_FORMAT,
    SUCCESS,
    WRONGPASSWORD,
    INVALID_USERNAME_OR_PASSWORD,
    INVALID_SPETIOAL,
    MALE_EXISTS,
    INVALID_MENU_ENTERED,
    NO_ACCESS,
    ENTER_NEW_PASSWORD;

}
